backend:
  image: us-central1-docker.pkg.dev/project-6b07c7a3-5303-403d-bf7/todo-app/todo-backend
  tag: latest
  port: 8000
  replicas: 1

frontend:
  image: us-central1-docker.pkg.dev/project-6b07c7a3-5303-403d-bf7/todo-app/todo-frontend
  tag: latest
  port: 3000
  replicas: 1

secrets:
  DATABASE_URL: ""
  BETTER_AUTH_SECRET: ""
  OPENAI_API_KEY: ""
  NEXT_PUBLIC_API_URL: ""
  BETTER_AUTH_URL: ""
