backend:
  image: todo-backend
  tag: v2
  port: 8000
  replicas: 1

frontend:
  image: todo-frontend
  tag: v2
  port: 3000
  replicas: 1

secrets:
  DATABASE_URL: ""
  BETTER_AUTH_SECRET: ""
  OPENAI_API_KEY: ""
  NEXT_PUBLIC_API_URL: ""
  BETTER_AUTH_URL: ""
